name: Kahiwacoffee
favicon: null
layout_spectrum: 0.88631
typography_spectrum: 0.6470362541731447
title: 'Tervetuloa !'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2018'
    - '#90c2d9'
    - '#fefefe'
    - '#48646b'
    - '#a08b7f'
  brandStrength: 0
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 0
purpose: []
