typography_spectrum: 0.6470362541731447
color:
  brandColors:
    - '#2d2018'
    - '#90c2d9'
    - '#fefefe'
    - '#48646b'
    - '#a08b7f'
  brandStrength: 0
  lightness: 1
  saturation: 0.5625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.92093
analytics:
  google: null
  facebook: null
  twitter: null
name: Kahiwacoffee
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Tervetuloa !
description: 'Kahvi, jolla on tarina'
purpose: []
