name: Kahiwacoffee
favicon: null
layout_spectrum: 0.5615748486015946
typography_spectrum: 0.6470362541731447
title: 'Tervetuloa !'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4032177876215428
  lightness: 0.10071990732103586
  saturation: 0.3498579759616405
  rhythmicContrast: 0.9013816106598824
purpose: []
